title: Muataz Albadri
email: muatazs.abed@gmail.com

description: >
  Scan-to-BIM & AI Automation Consultant helping engineering, construction,
  and asset owners transform reality data into reliable digital models.

remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
search: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

author:
  name: "Muataz Albadri"
  avatar: "/assets/images/Muataz.jpg"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/muataz-albadri-2290381a4/"

include:
  - pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
